### ISSUE TITLE
[BUG] No documentation 

### ISSUE THREAD

**Issue by guysoft** [PrometeoConseil/AudioBookSplitter#1]
**Describe the bug**
There is no documentation in the project page. There is no way for me to know how to use this, how to build it, since there are no released.

There are no requiremtns to understand what you need in order to build it, and no example of usage. 

**To Reproduce**

1. Go to project page
2. Try to understand how to use.

**Expected behavior**
There should be a README.md file, or equivelent which has steps to get this software usable.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]

**Comment by CrustyApplesniffer** [comment]
Done.
