### ISSUE TITLE
[question] how is ffprobe extracting the chapters?

### ISSUE THREAD

**Issue by guysoft** [PrometeoConseil/AudioBookSplitter#2]
Hey,
Is ffprobe looking for quiet gaps? or is it pulling the chapter data out of metadata inside the file?

**Comment by CrustyApplesniffer** [comment]
ffprobe is pulling data from mp3 file metadata.
Have a look into [ffprobe webpage](https://ffmpeg.org/ffprobe.html#Generic-options), search -show_chapters option.
