### ISSUE TITLE
[BUG] Problems with Windows CLI

### ISSUE THREAD

**Issue by KaraokeAmerica** [PrometeoConseil/AudioBookSplitter#3]
**Describe the bug**
I get perpetual issues with the path being too long when I try to run this in Windows10-x64

**To Reproduce**
1. ran this command line:
`C:\PrometeoAudiobookSplitter>AudioBookSplitterCmd.exe -s "C:\PrometeoAudiobooksplitter\tec\tec.mp3" -o "C:\output"`

**Expected behavior**
I expected it to create MP3 files for each chapter contained in source MP3.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser not a web based program, but I run Chrome, Firefox and Edge
 - Version N/A

**Additional context**
Issue referenced in this thread:
`https://github.com/openaudible/openaudible/issues/92#issuecomment-508569806`

Thsi is what I got when I ran in latest CMD line syntax suggestion:

Microsoft Windows [Version 10.0.18362.175]
(c) 2019 Microsoft Corporation. All rights reserved.

```
C:\PrometeoAudiobookSplitter>AudioBookSplitterCmd.exe -s "C:\PrometeoAudiobooksplitter\tec\tec.mp3" -o "C:\output"
![Untitled](https://user-images.githubusercontent.com/52175682/60687515-971a7800-9e74-11e9-87a8-dd3e0d12e254.jpg)


System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at AudioBookSplitterCmd.Program.Main(String[] args) in D:\Personnel\_repo\Audio Book Splitter\AudioBookSplitterCmd\Program.cs:line 90
Press any key to exit the program.
```
I tried a few variations of using it and even after restarting my CMD window and moving the working directory to a new location I now get this error anytime I try to run it:

![Untitled](https://user-images.githubusercontent.com/52175682/60687526-a8fc1b00-9e74-11e9-8ce8-d1f3e7426598.jpg)

I can't run it at all now:
```
C:\Program Files\PrometeoAudiobookSplitter>AudioBookSplitterCmd.exe -s "C:\Program Files\PrometeoAudiobooksplitter\tec\tec.mp3" -o "C:\output"
Access is denied.
```

Or:

```
C:\PrometeoAudiobookSplitter>AudioBookSplitterCmd.exe -s "C:\PrometeoAudiobooksplitter\tec\tec.mp3" -o "C:\output"
Access is denied.
```

**Comment by KaraokeAmerica** [comment]
Just tried moving all of it to my documents folder with same result:
```
C:\Users\flkar\Documents\Media Tools\PrometeoAudiobookSplitter>AudioBookSplitterCmd.exe -s "C:\Users\flkar\Documents\Media Tools\PrometeoAudiobooksplitter\tec\tec.mp3" -o "C:\Users\flkar\Documents\Media Tools\PrometeoAudiobooksplitter\tec\output"
Access is denied.
```
It's like Windows has blacklisted the executable.

**Comment by CrustyApplesniffer** [comment]
I've created an alpha version for you (https://github.com/PrometeoConseil/AudioBookSplitter/releases/tag/v1.1.82.7125-alpha)

I've added a -p option (or --PreferShortTargetFolder) 
Try the following:
```C:\PrometeoAudiobookSplitter>AudioBookSplitterCmd.exe -s "C:\PrometeoAudiobooksplitter\tec\tec.mp3" -o "C:\output" -p```
